"""add users table

Revision ID: f61fe514b7c7
Revises: 
Create Date: 2026-02-27 23:04:16.915957

"""
from alembic import op
import sqlalchemy as sa


revision = 'f61fe514b7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
